Integrate scripts and support Debian.

diff --git a/build-llama.cpp-rocm.in b/build-llama.cpp-rocm.in
--- a/build-llama.cpp-rocm.in
+++ b/build-llama.cpp-rocm.in
@@ -18,6 +18,7 @@
 : ${GIT_CMD:='@GIT_CMD@'}
 : ${GREP_CMD:='@GREP_CMD@'}
 : ${MAKE_CMD:='@MAKE_CMD@'}
+: ${NPROC_CMD:='@NPROC_CMD@'}
 : ${PATCH_CMD:='@PATCH_CMD@'}
 : ${PIP_CMD:="${HOME}/.asdf/shims/pip"}
 : ${READLINK_CMD:='@READLINK_CMD@'}
@@ -27,7 +28,11 @@
 : ${TEE_CMD:='@TEE_CMD@'}
 
 : ${INSTALL_PREFIX:='/usr/local'}
+: ${AMDGPU_TARGET:='gfx1151'}
+: ${ONEAPI_ROOT:='/opt/intel/oneapi'}
 : ${ROCM_ROOT:='/opt/rocm'}
+: ${OMPI_ROOT:='/usr/local'}
+: ${UCX_ROOT:='/usr/local'}
 
 # OS-agnstoic readlink for existent files/directories.
 resolve-existing ()
@@ -56,26 +61,39 @@ set-alternatives ()
 
 check-oneapi-env ()
 {
-    if test ."$ONEAPI_ROOT" = .''; then
-        if test ! -d /opt/intel/oneapi; then
-            $SUDO_CMD -i ${script_dir}/install-intel-oneapi-hpc || return $?
-        fi
+    local oneapi_root=$1
+
+    if test ! -d "$oneapi_root"; then
+        $SUDO_CMD -i ${script_dir}/install-intel-oneapi-hpc || return $?
+    fi
+
+    if ! command -v icx >/dev/null; then
         source /opt/intel/oneapi/setvars.sh
     fi
 }
 
 check-rocm-env ()
 {
-    if test ! -d "${ROCM_ROOT}/bin"; then
-        $SUDO_CMD -i ${script_dir}/install-rocm-binaries || return $?
+    local amdgpu_target=$1
+    local ucx_root=$2
+    local ompi_root=$3
+    local rocm_root=$4
+
+    if test ! -d "${rocm_root}/bin"; then
+        $SUDO_CMD -i ${script_dir}/install-rocm-binaries \
+                  "$amdgpu_target" \
+                  "$ucx_root" \
+                  "$ompi_root" \
+                  "$rocm_root" \
+            || return $?
     fi
 
-    if ! $GREP_CMD -q cuda <<<$PATH; then
-        export PATH=/usr/local/cuda/bin:${PATH}
+    if ! $GREP_CMD -q rocm <<<$PATH; then
+        export PATH=${rocm_root}/bin:${PATH}
     fi
 
     if ! command -v rocminfo >/dev/null; then
-        echo 'Error: ROCm installation not found in /opt/rocm/' >&2
+        echo "Error: ROCm installation not found in ${ROCM_ROOT}" >&2
         return 1
     fi
 }
@@ -138,10 +156,10 @@ clone-repo ()
     local srcdir=$2
 
     if test -d "${srcdir}/.git"; then
-        git -C "$srcdir" pull --rebase || return $?
+        $GIT_CMD -C "$srcdir" pull --rebase || return $?
     else
-        install -d -m 0755 "${srcdir%/*}" || return $?
-        git -C "${srcdir%/*}" clone "$repo_url" "${srcdir##*/}" || return $?
+        $INSTALL_CMD -d -m 0755 "${srcdir%/*}" || return $?
+        $GIT_CMD -C "${srcdir%/*}" clone "$repo_url" "${srcdir##*/}" || return $?
     fi
 }
 
@@ -154,25 +172,24 @@ patch-repo ()
 
     up_to_date=$(
         $GIT_CMD -C "$srcdir" log \
-                 --pretty=reference --grep 'Update Python requirements.'
+                 --pretty=reference --grep 'Assign golang path.'
            ) || return $?
 
-    if test -z "$up_to_date"; then
-        local patchfile=''
-
-        for patchfile in "${patchdir}/"*.diff; do
-            $PATCH_CMD -d "$srcdir" <"$patchfile" || return $?
-        done
-
-        $CAT_CMD >&2 <<'EOF'
-!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
-!! Enter git credentials for commit: 'Update Python requirements.': !!
-!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
-EOF
-        $GIT_CMD -C "$srcdir" commit -a -m 'Update Python requirements.'
+    if test ."$up_to_date" != .''; then
+        return 0
     fi
+    local patchfile=''
 
-    $PIP_CMD install -U -r "${srcdir}/requirements.txt" || return $?
+    for patchfile in "${patchdir}/"*.diff; do
+        $PATCH_CMD -d "$srcdir" <"$patchfile" || return $?
+    done
+
+    $CAT_CMD >&2 <<'EOF'
+!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
+!! Enter git credentials for commit: 'Assign golang path.': !!
+!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
+EOF
+    $GIT_CMD -C "$srcdir" commit -a -m 'Assign golang path.'
 }
 
 build-llama.cpp ()
@@ -185,19 +202,21 @@ build-llama.cpp ()
     HIPCXX="$(hipconfig -l)/clang" \
           HIP_PATH="$(hipconfig -R)" \
           HIP_PLATFORM=amd \
-          $CMAKE_CMD -B "$builddir" \
-          -DCMAKE_INSTALL_PREFIX="${INSTALL_PREFIX}" \
-          -DCMAKE_INSTALL_RPATH="${INSTALL_PREFIX}/lib64;${ONEAPI_ROOT}/compiler/latest/lib;${ONEAPI_ROOT}/mkl/latest/lib" \
-          -DGGML_HIP=ON \
-          -DGGML_HIP_ROCWMMA_FATTN=ON \
-          -DAMDGPU_TARGETS=gfx1151 \
-          -DCMAKE_BUILD_TYPE=Release \
-          -DGGML_BLAS=ON \
-          -DGGML_BLAS_VENDOR=Intel10_64lp \
-          -DCMAKE_C_COMPILER=icx \
-          -DCMAKE_CXX_COMPILER=icpx \
-          -DGGML_NATIVE=ON \
-          -DLLAMA_CURL=ON \
+          $CMAKE_CMD \
+              -S "$srcdir" \
+              -B "$builddir" \
+              -DCMAKE_INSTALL_PREFIX="${INSTALL_PREFIX}" \
+              -DCMAKE_INSTALL_RPATH="${INSTALL_PREFIX}/lib64;${ONEAPI_ROOT}/compiler/latest/lib;${ONEAPI_ROOT}/mkl/latest/lib" \
+              -DGGML_HIP=ON \
+              -DGGML_HIP_ROCWMMA_FATTN=ON \
+              -DAMDGPU_TARGETS=gfx1151 \
+              -DCMAKE_BUILD_TYPE=Release \
+              -DGGML_BLAS=ON \
+              -DGGML_BLAS_VENDOR=Intel10_64lp \
+              -DCMAKE_C_COMPILER=icx \
+              -DCMAKE_CXX_COMPILER=icpx \
+              -DGGML_NATIVE=ON \
+              -DLLAMA_CURL=ON \
         || return $?
 
 # OneAPI CMake options
@@ -208,7 +227,8 @@ build-llama.cpp ()
 #               -DCMAKE_CXX_COMPILER=icpx \
 #               -DGGML_NATIVE=ON \
 
-    $MAKE_CMD -C "$builddir" -j60 |& $TEE_CMD "${builddir}/build.OUT"
+    $MAKE_CMD -C "$builddir" -j$($NPROC_CMD) |&
+        $TEE_CMD "${builddir}/build.OUT"
 }
 
 if test ."$0" = ."${BASH_SOURCE[0]}"; then
@@ -232,6 +252,11 @@ if test ."$0" = ."${BASH_SOURCE[0]}"; then
               ) || true
 
     declare abs_srcdir=${1:-"$top_srcdir"}
+    declare amdgpu_target=${2:-"$AMDGPU_TARGET"}
+    declare rocm_root=${3:-"$ROCM_ROOT"}
+    declare ompi_root=${4:-"$OMPI_ROOT"}
+    declare ucx_root=${5:-"$UCX_ROOT"}
+    declare oneapi_root=${6:-"$ONEAPI_ROOT"}
 
     declare llama_repo_url='https://github.com/ggml-org/llama.cpp.git'
     declare llama_srcdir=${script_dir}/src/llama.cpp
@@ -240,8 +265,9 @@ if test ."$0" = ."${BASH_SOURCE[0]}"; then
 
     echo "Building llama.cpp with ROCm and Intel cuBLAS support" >&2
 
-    check-oneapi-env || exit $?
-    check-rocm-env || exit $?
+    check-oneapi-env "$oneapi_root" || exit $?
+    check-rocm-env "$amdgpu_target" "$ucx_root" "$ompi_root" "$rocm_root" \
+        || exit $?
     verify-python "$py_version" || exit $?
     clone-repo "$llama_repo_url" "$llama_srcdir" || exit $?
     # patch-repo "$llama_srcdir" "$llama_patchdir" || exit $?
diff --git a/install-rocm-binaries.in b/install-rocm-binaries.in
--- a/install-rocm-binaries.in
+++ b/install-rocm-binaries.in
@@ -6,41 +6,46 @@
 # builds.
 #
 : ${CURL_CMD:='@CURL_CMD@'}
-: ${ED_CMD:='@ED_CMD@'}
 : ${GZIP_CMD:='@GZIP_CMD@'}
 : ${INSTALL_CMD:='@INSTALL_CMD@'}
 : ${JQ_CMD:='@JQ_CMD@'}
 : ${RM_CMD:='@RM_CMD@'}
+: ${SED_CMD:='@SED_CMD@'}
 : ${SUDO_CMD:='@SUDO_CMD@'}
 : ${TAR_CMD:='@TAR_CMD@'}
 : ${TOUCH_CMD:='@TOUCH_CMD@'}
+
+: ${AMDGPU_TARGET:='gfx1151'}
+: ${ROCM_ROOT:='/opt/rocm'}
+: ${OMPI_ROOT:='/usr/local'}
+: ${UCX_ROOT:='/usr/local'}
 
 get-latest-build ()
 {
     local target=linux-${1}
     local index_url=${2}/index.html
 
-    $ED_CMD -e 'v/const files = /d' \
-            -e 's^^{ "files": ^' \
-            -e 's^];^] }^' \
-            -e "w !$JQ_CMD -r '[.files[] | select(.name | contains(\"'$target'\"))] | . | max_by(.mtime) | .name'" \
-            <($CURL_CMD -sSL --no-buffer "$index_url") 2>/dev/null
+    $CURL_CMD -sSL --no-buffer "$index_url" |
+        $SED_CMD -e '/const files = /!d' \
+                 -e 's^^{ "files": ^' \
+                 -e 's^];^] }^' |
+        $JQ_CMD -r '[.files[] | select(.name | contains("'$target'"))] | . | max_by(.mtime) | .name'
 }
 
 is-installed ()
 {
-    local rocmdir=$1
+    local rocm_root=$1
     local name=$2
 
-    test -f "${rocmdir}/${name%.tar.gz}"
+    test -f "${rocm_root}/${name%.tar.gz}"
 }
 
 initialize-installdir ()
 {
-    local rocmdir=$1
+    local rocm_root=$1
 
-    $SUDO_CMD $RM_CMD -rf "$rocmdir"
-    $SUDO_CMD $INSTALL_CMD -d -m 0755 "$rocmdir"
+    $SUDO_CMD $RM_CMD -rf "$rocm_root"
+    $SUDO_CMD $INSTALL_CMD -d -m 0755 "$rocm_root"
 }
 
 fetch-compressed-archive ()
@@ -55,18 +60,52 @@ fetch-compressed-archive ()
 
 extract-archive-stream ()
 {
-    local rocmdir=$1
+    local rocm_root=$1
 
     $GZIP_CMD -cd - |
-        $SUDO_CMD $TAR_CMD -C "$rocmdir" -xf -
+        $SUDO_CMD $TAR_CMD -C "$rocm_root" -xf -
 }
 
 record-archive-name ()
 {
-    local rocmdir=$1
+    local rocm_root=$1
     local name=$2
 
-    $SUDO_CMD $TOUCH_CMD "${rocmdir}/${name%.tar.gz}"
+    $SUDO_CMD $TOUCH_CMD "${rocm_root}/${name%.tar.gz}"
+}
+
+set-ldconfig ()
+{
+    local rocm_root=$1
+
+    if test ! -f /etc/ld.so.conf.d/rocm.conf; then
+        $SUDO_CMD $TEE_CMD >/dev/null /etc/ld.so.conf.d/rocm.conf <<<"${rocm_root}/lib" || return $?
+        $SUDO_CMD $LDCONFIG_CMD || return $?
+    fi
+}
+
+check-ompi-env ()
+{
+    local ucx_root=$1
+    local ompi_root=$1
+    local rocm_root=$1
+
+    if ! command -v "${ompi_root}/bin/ompi_info" >/dev/null; then
+        $SUDO_CMD -i ${script_dir}/install-opmi \
+                  "$ucx_root" \
+                  "$ompi_root" \
+                  "$rocm_root" \
+            || return $?
+    fi
+
+    if ! $GREP_CMD -q "${ompi_root}/bin" <<<$PATH; then
+        export PATH=${ompi_root}/bin:${PATH}
+    fi
+
+    if ! command -v ompi_info >/dev/null; then
+        echo "${script_name}: OMPI installation not found in ${ompi_root}" >&2
+        return 1
+    fi
 }
 
 if test ."$0" = ."${BASH_SOURCE[0]}"; then
@@ -74,28 +113,32 @@ if test ."$0" = ."${BASH_SOURCE[0]}"; then
 
     declare script=''
     declare script_name=''
+    declare script_dir=''
 
     script=$(readlink -e "$0")
     script_name=${script##*/}
+    script_dir=${script%/*}
 
-    declare gfx_target=${1:-'gfx1151'}
-    declare rocm_rootdir=${2:-'/opt/rocm'}
+    declare amdgpu_target=${1:-"$AMDGPU_TARGET"}
+    declare ucx_root=${2:-"$UCX_ROOT"}
+    declare ompi_root=${3:-"$OMPI_ROOT"}
+    declare rocm_root=${4:-"$ROCM_ROOT"}
 
     declare rocm_nightly_url='https://therock-nightly-tarball.s3.amazonaws.com'
-
-
     declare latest_build=''
 
-    if ! latest_build=$(get-latest-build "$gfx_target" "$rocm_nightly_url"); then
-        echo "${script_name}: ${gfx_target}: Not found" >&2
+    if ! latest_build=$(get-latest-build "$amdgpu_target" "$rocm_nightly_url"); then
+        echo "${script_name}: ${amdgpu_target}: Not found" >&2
         exit 1
-    elif is-installed "$rocm_rootdir" "$latest_build"; then
+    elif is-installed "$rocm_root" "$latest_build"; then
         echo "${script_name}: ${latest_build}: Already installed" >&2
         exit 0
     fi
 
-    initialize-installdir "$rocm_rootdir" || exit $?
+    initialize-installdir "$rocm_root" || exit $?
     fetch-compressed-archive "$rocm_nightly_url" "$latest_build" |
-        extract-archive-stream "$rocm_rootdir" || exit $?
-    record-archive-name "$rocm_rootdir" "$latest_build"
+        extract-archive-stream "$rocm_root" || exit $?
+    record-archive-name "$rocm_root" "$latest_build"
+    set-ldconfig "$rocm_root" || exit $?
+    check-ompi-env "$ucx_root" "$ompi_root" "$rocm_root" || exit $?
 fi
diff --git a/install-ucx.in b/install-ucx.in
--- a/install-ucx.in
+++ b/install-ucx.in
@@ -2,12 +2,31 @@
 #
 # @(#) install-ucx
 #
-setup-rocm ()
-{
-    local rocm_target=$1
-    local rocm_root=$2
+: ${CAT_CMD:='@CAT_CMD@'}
+: ${GIT_CMD:='@GIT_CMD@'}
+: ${INSTALL_CMD:='@INSTALL_CMD@'}
+: ${MAKE_CMD:='@MAKE_CMD@'}
+: ${NPROC_CMD:='@NPROC_CMD@'}
+: ${PATCH_CMD:='@PATCH_CMD@'}
+: ${READLINK_CMD:='@READLINK_CMD@'}
+: ${SUDO_CMD:='@SUDO_CMD@'}
+: ${TEE_CMD:='@TEE_CMD@'}
 
-    "${script_dir}/install-rocm-binaries" "$rocm_target" "$rocm_root"
+: ${ROCM_ROOT:='/opt/rocm'}
+: ${UCX_ROOT:='/usr/local'}
+
+check-rocm-env ()
+{
+    local rocm_root=$1
+
+    if ! command -v "${rocm_root}/bin/rocminfo" >/dev/null; then
+        echo "${script_name}: ROCM installation not found in ${rocm_root}" >&2
+        return 1
+    fi
+
+    if ! $GREP_CMD -q "${rocm_root}/bin" <<<$PATH; then
+        export PATH=${rocm_root}/bin:${PATH}
+    fi
 }
 
 clone-repo ()
@@ -16,22 +35,40 @@ clone-repo ()
     local srcdir=$2
 
     if test -d "${srcdir}/.git"; then
-        git -C "$srcdir" pull --rebase || return $?
+        $GIT_CMD -C "$srcdir" pull --rebase || return $?
     else
-        install -d -m 0755 "${srcdir%/*}" || return $?
-        git -C "${srcdir%/*}" clone "$repo_url" "${srcdir##*/}" || return $?
+        $INSTALL_CMD -d -m 0755 "${srcdir%/*}" || return $?
+        $GIT_CMD -C "${srcdir%/*}" clone "$repo_url" "${srcdir##*/}" || return $?
     fi
 }
 
 patch-repo ()
 {
     local srcdir=$1
-    local patch_file=$2
+    local patchdir=$2
 
-    if git -C "$srcdir" apply --index "$patch_file"; then
-        echo 'Git commit: Add golang path.'
-        git -C "$srcdir" commit -m 'Assign golang path.'
+    local up_to_date=''
+
+    up_to_date=$(
+        $GIT_CMD -C "$srcdir" log \
+                 --pretty=reference --grep 'Assign golang path.'
+           ) || return $?
+
+    if test ."$up_to_date" != .''; then
+        return 0
     fi
+    local patchfile=''
+
+    for patchfile in "${patchdir}/"*.diff; do
+        $PATCH_CMD -p1 -d "$srcdir" <"$patchfile" || return $?
+    done
+
+    $CAT_CMD >&2 <<'EOF'
+!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
+!! Enter git credentials for commit: 'Assign golang path.': !!
+!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
+EOF
+    $GIT_CMD -C "$srcdir" commit -a -m 'Assign golang path.'
 }
 
 build-ucx ()
@@ -41,7 +78,7 @@ build-ucx ()
 
     local builddir=${srcdir}/build
 
-    install -d -m 0755 "$builddir" || return $?
+    $INSTALL_CMD -d -m 0755 "$builddir" || return $?
 
     pushd "$srcdir" >/dev/null
     ./autogen.sh || return $?
@@ -52,15 +89,19 @@ build-ucx ()
           --prefix="$install_prefix" \
           --libdir="${install_prefix}/lib" \
           --with-rocm=/opt/rocm \
+          --enable-mt \
           --with-go=$(command -v go) \
           --without-knem \
           --disable-logging \
           --disable-debug \
           --disable-assertions \
           --disable-params-check \
+          --with-avx \
+          --with-sse42 \
         || return $?
-    make clean || return $?
-    make -j$(nproc) | tee "${builddir}/build.OUT" || return $?
+    $MAKE_CMD clean || return $?
+    $MAKE_CMD -j$($NPROC_CMD) |&
+        $TEE_CMD "${builddir}/build.OUT" || return $?
     popd >/dev/null
 }
 
@@ -70,7 +111,7 @@ install-ucx ()
 
     local builddir=${srcdir}/build
 
-    sudo -i make -C "$builddir" install
+    $SUDO_CMD -i $MAKE_CMD -C "$builddir" install
 }
 
 if test ."$0" = ."${BASH_SOURCE[0]}"; then
@@ -80,21 +121,28 @@ if test ."$0" = ."${BASH_SOURCE[0]}"; then
     declare script_name=''
     declare script_dir=''
 
-    script=$(readlink -e "$0") || exit $?
+    script=$($READLINK_CMD -e "$0") || exit $?
     script_name=${script##*/}
     script_dir=${script%/*}
 
-    declare rocm_target=${1:-'gfx1151'}
-    declare rocm_root=${2:-'/opt/rocm'}
-    declare ucx_root=${3:-'/usr/local'}
+    declare rocm_root=${1:-"$ROCM_ROOT"}
+    declare ucx_root=${2:-"$UCX_ROOT"}
 
     declare ucx_repo_url='https://github.com/openucx/ucx.git'
     declare ucx_srcdir=${script_dir}/src/ucx
-    declare top_srcdir=$(git rev-parse --show-toplevel)
+    declare top_srcdir=''
 
-    setup-rocm "$rocm_target" "$rocm_root" || exit $?
+    top_srcdir=$(
+        cd "$script_dir" && $GIT_CMD rev-parse --show-toplevel
+              ) || exit $?
+
+    declare ucx_patchdir=${top_srcdir}/patches/ucx
+
+    echo "Building and installing UCX with ROCm support" >&2
+
+    check-rocm-env "$rocm_root" || exit $?
     clone-repo "$ucx_repo_url" "$ucx_srcdir" || exit $?
-    patch-repo "$ucx_srcdir" "${top_srcdir}/patches/ucx/patch-ucx.diff" || exit $?
+    patch-repo "$ucx_srcdir" "$ucx_patchdir" || exit $?
     build-ucx "$ucx_srcdir" "$ucx_root" || exit $?
     install-ucx "$ucx_srcdir" || exit $?
 fi
